# Generated by Django 5.0.6 on 2026-01-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QHR_Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominal", models.FloatField(blank=True, db_column="Nominal (ohm)")),
                ("date", models.DateTimeField(blank=True, db_column="Date")),
                ("end_time", models.DateTimeField(blank=True, db_column="End Time")),
                (
                    "ccc_primary_current",
                    models.FloatField(blank=True, db_column="CCC Primary Current"),
                ),
                ("cycle_time", models.FloatField(blank=True, db_column="Cycle Time")),
                (
                    "ccc_nominal_ratio",
                    models.CharField(
                        blank=True, db_column="CCC Nominal Ratio", max_length=16
                    ),
                ),
                (
                    "reference_sn",
                    models.CharField(
                        blank=True, db_column="Reference SN", max_length=45
                    ),
                ),
                (
                    "serial",
                    models.CharField(blank=True, db_column="Serial", max_length=45),
                ),
                ("c", models.FloatField(blank=True, db_column="C")),
                ("sd_c_field", models.FloatField(blank=True, db_column="SD (C)")),
                ("pred_c_field", models.FloatField(blank=True, db_column="Pred (C)")),
                ("ccc_r", models.FloatField(blank=True, db_column="CCC R")),
                ("meassets", models.IntegerField(blank=True, db_column="MeasSets")),
                ("pressure", models.FloatField(blank=True, db_column="Pressure")),
                ("ref_temp", models.FloatField(blank=True, db_column="Ref Temp")),
                ("meas_temp", models.FloatField(blank=True, db_column="Unknown Temp")),
                ("c1", models.FloatField(blank=True, db_column="C1")),
                ("c2", models.FloatField(blank=True, db_column="C2")),
                ("ccc_deltar", models.FloatField(blank=True, db_column="CCC deltaR")),
                ("sd_c1_field", models.FloatField(blank=True, db_column="SD (C1)")),
                ("sd_c2_field", models.FloatField(blank=True, db_column="SD (C2)")),
                ("samples", models.FloatField(blank=True, db_column="Samples")),
                (
                    "samples_used",
                    models.FloatField(blank=True, db_column="Samples Used"),
                ),
                (
                    "ccc_timing",
                    models.CharField(blank=True, db_column="CCC Timing", max_length=45),
                ),
                (
                    "ref_corrected",
                    models.FloatField(blank=True, db_column="Ref Corrected"),
                ),
                ("comments", models.TextField(blank=True, db_column="Comments")),
                ("ref_pcr", models.FloatField(blank=True, db_column="Ref PCR")),
                ("ref_tcr", models.FloatField(blank=True, db_column="Ref TCR")),
                (
                    "ref_tcr_beta",
                    models.FloatField(blank=True, db_column="Ref TCR Beta"),
                ),
                ("unknown_pcr", models.FloatField(blank=True, db_column="Unknown PCR")),
                ("unknown_tcr", models.FloatField(blank=True, db_column="Unknown TCR")),
                (
                    "unknown_tcr_beta",
                    models.FloatField(blank=True, db_column="Unknown TCR Beta"),
                ),
                ("guard", models.FloatField(blank=True, db_column="Guard")),
                ("ccc_bvd", models.FloatField(blank=True, db_column="CCC BVD")),
                (
                    "ccc_feedback_type",
                    models.CharField(
                        blank=True, db_column="CCC Feedback type", max_length=50
                    ),
                ),
                ("ccc_feedin", models.FloatField(blank=True, db_column="CCC Feedin")),
                (
                    "external_power",
                    models.CharField(
                        blank=True, db_column="External Power", max_length=5
                    ),
                ),
                ("room_rh", models.FloatField(blank=True, db_column="Room RH")),
                (
                    "magnicon_com_temp",
                    models.FloatField(blank=True, db_column="Magnicon com temp"),
                ),
                (
                    "magnicon_cn_temp",
                    models.FloatField(blank=True, db_column="Magnicon cn temp"),
                ),
                (
                    "magnicon_nv_temp",
                    models.FloatField(blank=True, db_column="Magnicon nv temp"),
                ),
                (
                    "system_id",
                    models.CharField(blank=True, db_column="System ID", max_length=100),
                ),
                (
                    "service_id",
                    models.CharField(blank=True, db_column="Service ID", max_length=20),
                ),
                (
                    "process",
                    models.CharField(blank=True, db_column="Process", max_length=100),
                ),
                (
                    "magnetic_field",
                    models.FloatField(blank=True, db_column="Magnetic field"),
                ),
                (
                    "sample_temperature",
                    models.FloatField(blank=True, db_column="Sample temperature"),
                ),
                (
                    "contacts",
                    models.CharField(
                        blank=True,
                        db_column="I and V probes (I+, I-, V+, V-)",
                        max_length=20,
                    ),
                ),
                (
                    "char_cryostat",
                    models.FloatField(
                        blank=True, db_column="Characterization cryostat"
                    ),
                ),
                ("area", models.CharField(blank=True, db_column="Area", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="search_qconductance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        db_column="Serial",
                        help_text="<em>Serial number of the QHR device</em>",
                        max_length=20,
                    ),
                ),
                (
                    "nominal",
                    models.CharField(
                        blank=True,
                        db_column="Nominal",
                        help_text="<em>Nominal standard value in ohms</em>",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "process_name",
                    models.CharField(
                        blank=True,
                        db_column="Process name",
                        help_text="<em>Name of the process</em>",
                        max_length=30,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        db_column="Format",
                        help_text="<em>Download file format (xlsx if left blank)</em>",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
