# Generated by Django 5.0.6 on 2026-01-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qconductance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qhr_process",
            name="char_cryostat",
            field=models.CharField(
                blank=True, db_column="Characterization cryostat", max_length=20
            ),
        ),
    ]
