# Generated by Django 5.0.6 on 2026-01-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qconductance", "0002_alter_qhr_process_char_cryostat"),
    ]

    operations = [
        migrations.CreateModel(
            name="filename",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.CharField(blank=True, max_length=100)),
                ("uploaded_filename", models.TextField(blank=True)),
            ],
        ),
    ]
