# Generated by Django 5.0.6 on 2026-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qconductance", "0003_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_qconductance",
            name="serial",
            field=models.CharField(
                blank=True,
                db_column="Serial",
                help_text="<em>Serial number of the QHR device</em>",
                max_length=40,
            ),
        ),
    ]
