# Generated by Django 5.2.17 on 2026-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qconductance", "0005_alter_search_qconductance_nominal"),
    ]

    operations = [
        migrations.AddField(
            model_name="qhr_process",
            name="carrier_density",
            field=models.FloatField(blank=True, db_column="Carrier density", null=True),
        ),
        # MySQL adds new columns at the end of the table. Move this one next to the
        # cryostat so exports (SELECT *) list the columns in the model's field order.
        migrations.RunSQL(
            "ALTER TABLE `qconductance_qhr_process` MODIFY COLUMN `Carrier density` "
            "double precision NULL AFTER `Characterization cryostat`",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
