# Generated by Django 5.0.6 on 2024-10-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="nominal",
            field=models.FloatField(
                blank=True,
                db_column="Nominal",
                help_text="<em>Nominal standard value in ohms</em>",
                max_length=20,
                null=True,
            ),
        ),
    ]
