# Generated by Django 4.1.2 on 2024-05-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="scaling_ccc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominal", models.FloatField(blank=True, db_column="Nominal")),
                (
                    "system_id",
                    models.CharField(blank=True, db_column="System ID", max_length=10),
                ),
                (
                    "date",
                    models.CharField(blank=True, db_column="Date", max_length=100),
                ),
                (
                    "ccc_primary_current",
                    models.FloatField(blank=True, db_column="CCC Primary Current"),
                ),
                ("meas_delay", models.FloatField(blank=True, db_column="Meas Delay")),
                (
                    "ccc_nom_ratio",
                    models.CharField(
                        blank=True, db_column="CCC Nom Ratio", max_length=10
                    ),
                ),
                (
                    "comments",
                    models.CharField(blank=True, db_column="Comments", max_length=200),
                ),
                (
                    "serial",
                    models.CharField(blank=True, db_column="Serial", max_length=20),
                ),
                ("c", models.FloatField(blank=True, db_column="C")),
                ("sd_c_field", models.FloatField(blank=True, db_column="SD (C)")),
                ("pred_c_field", models.FloatField(blank=True, db_column="Pred (C)")),
                (
                    "reference_sn",
                    models.CharField(
                        blank=True, db_column="Reference SN", max_length=45
                    ),
                ),
                ("ccc_r", models.FloatField(blank=True, db_column="CCC R")),
                ("meassets", models.IntegerField(blank=True, db_column="MeasSets")),
                ("pressure", models.FloatField(blank=True, db_column="Pressure")),
                ("unknown_temp", models.FloatField(blank=True, db_column="Meas Temp")),
                (
                    "unknown_temp_2",
                    models.FloatField(blank=True, db_column="Meas Temp 2"),
                ),
                ("dvm_nplc", models.FloatField(blank=True, db_column="DVM NPLC")),
                (
                    "dvm_readings",
                    models.IntegerField(blank=True, db_column="DVM readings"),
                ),
                (
                    "ccc_timing",
                    models.CharField(blank=True, db_column="CCC Timing", max_length=45),
                ),
                (
                    "service_id",
                    models.CharField(blank=True, db_column="Service ID", max_length=20),
                ),
                (
                    "process",
                    models.CharField(blank=True, db_column="Process", max_length=100),
                ),
                ("area", models.CharField(blank=True, db_column="Area", max_length=20)),
            ],
        ),
    ]
