# Generated by Django 4.1.2 on 2024-05-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0002_scaling_ccc"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="magnicon_ccc",
            new_name="Magnicon_CCC_Process",
        ),
        migrations.RenameModel(
            old_name="scaling_ccc",
            new_name="Scaling_CCC_Process",
        ),
        migrations.RenameModel(
            old_name="thomas_dcc",
            new_name="Thomas_Process",
        ),
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="format",
            field=models.CharField(blank=True, db_column="Format", max_length=100),
        ),
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="model_no",
            field=models.CharField(blank=True, db_column="Model", max_length=100),
        ),
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="process_name",
            field=models.CharField(
                blank=True, db_column="Process name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="serial",
            field=models.CharField(blank=True, db_column="Filename", max_length=100),
        ),
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="service_id",
            field=models.CharField(blank=True, db_column="Service Id", max_length=100),
        ),
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="std_manufacturer",
            field=models.CharField(
                blank=True, db_column="Standard Manufacturer", max_length=100
            ),
        ),
    ]
