# Generated by Django 5.0.6 on 2024-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0002_alter_search_standard_resistor_nominal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="nominal",
            field=models.FloatField(
                blank=True,
                db_column="Nominal",
                default=0,
                help_text="<em>Nominal standard value in ohms</em>",
                max_length=20,
            ),
        ),
    ]
