# Generated by Django 4.1.2 on 2024-05-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0003_rename_magnicon_ccc_magnicon_ccc_process_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="serial",
            field=models.CharField(blank=True, db_column="Serial", max_length=100),
        ),
    ]
