# Generated by Django 5.0.6 on 2024-10-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0007_alter_search_standard_resistor_nominal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warshawsky_process",
            name="meas_voltage",
            field=models.CharField(blank=True, db_column="Meas Voltage", max_length=10),
        ),
    ]
