# Generated by Django 5.0.6 on 2024-10-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0008_alter_warshawsky_process_meas_voltage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_components",
            field=models.TextField(blank=True, db_column="CCC Components", null=True),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_i_fb1",
            field=models.FloatField(blank=True, db_column="CCC I FB1", null=True),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_i_fb2",
            field=models.FloatField(blank=True, db_column="CCC I FB2", null=True),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_r",
            field=models.FloatField(blank=True, db_column="CCC R", null=True),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_timing",
            field=models.CharField(
                blank=True, db_column="CCC Timing", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="dvm_nplc",
            field=models.FloatField(blank=True, db_column="DVM NPLC", null=True),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="dvm_readings",
            field=models.IntegerField(blank=True, db_column="DVM readings", null=True),
        ),
    ]
