# Generated by Django 5.0.6 on 2024-10-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0009_alter_hr3100_process_ccc_components_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_i_fb1",
            field=models.CharField(
                blank=True, db_column="CCC I FB1", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_i_fb2",
            field=models.CharField(
                blank=True, db_column="CCC I FB2", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_r",
            field=models.CharField(
                blank=True, db_column="CCC R", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="dvm_nplc",
            field=models.CharField(
                blank=True, db_column="DVM NPLC", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="dvm_readings",
            field=models.CharField(
                blank=True, db_column="DVM readings", max_length=10, null=True
            ),
        ),
    ]
