# Generated by Django 5.0.6 on 2024-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0010_alter_hr3100_process_ccc_i_fb1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="system_id",
            field=models.CharField(blank=True, db_column="System ID", max_length=20),
        ),
    ]
