# Generated by Django 5.0.6 on 2024-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0011_alter_hr3100_process_system_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_nom_ratio",
            field=models.CharField(
                blank=True, db_column="CCC Nom Ratio", max_length=20
            ),
        ),
    ]
