# Generated by Django 5.0.6 on 2024-10-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0012_alter_hr3100_process_ccc_nom_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_i_fb1",
            field=models.CharField(
                blank=True, db_column="CCC I FB1", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hr3100_process",
            name="ccc_i_fb2",
            field=models.CharField(
                blank=True, db_column="CCC I FB2", max_length=20, null=True
            ),
        ),
    ]
