# Generated by Django 5.0.6 on 2024-10-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0014_alter_hr3100_process_ccc_r"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="sd_c_field",
            field=models.CharField(
                blank=True, db_column="SD (C)", max_length=20, null=True
            ),
        ),
    ]
