# Generated by Django 5.0.6 on 2024-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0015_alter_hr3100_process_sd_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="meassets",
            field=models.FloatField(blank=True, db_column="MeasSets"),
        ),
    ]
