# Generated by Django 5.0.6 on 2024-10-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0016_alter_hr3100_process_meassets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="pred_c_field",
            field=models.CharField(
                blank=True, db_column="Pred (C)", max_length=20, null=True
            ),
        ),
    ]
