# Generated by Django 5.0.6 on 2024-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0017_alter_hr3100_process_pred_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="format",
            field=models.CharField(
                blank=True,
                db_column="Format",
                help_text="<em>Download file format (xlsx if left blank)</em>",
                max_length=10,
            ),
        ),
    ]
