# Generated by Django 5.0.6 on 2024-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0018_alter_search_standard_resistor_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="mi_range",
            field=models.CharField(blank=True, db_column="MI Range", max_length=100),
        ),
        migrations.AlterField(
            model_name="mi_6010b_process",
            name="mi_range",
            field=models.CharField(blank=True, db_column="MI Range", max_length=100),
        ),
        migrations.AlterField(
            model_name="mi_6010c_process",
            name="mi_range",
            field=models.CharField(blank=True, db_column="MI Range", max_length=100),
        ),
        migrations.AlterField(
            model_name="mi_6010q_process",
            name="mi_range",
            field=models.CharField(blank=True, db_column="MI Range", max_length=100),
        ),
        migrations.AlterField(
            model_name="mi_6010sw_process",
            name="mi_range",
            field=models.CharField(blank=True, db_column="MI Range", max_length=100),
        ),
        migrations.AlterField(
            model_name="mi_6020q_process",
            name="mi_range",
            field=models.CharField(blank=True, db_column="MI Range", max_length=100),
        ),
    ]
