# Generated by Django 5.0.6 on 2024-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0019_alter_mi_6000b_process_mi_range_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="pred_c_field",
            field=models.CharField(blank=True, db_column="Pred (C)", max_length=20),
        ),
    ]
