# Generated by Django 5.0.6 on 2024-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0020_alter_nist_aab_process_pred_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="room_temp",
            field=models.CharField(
                blank=True, db_column="Room Temp", max_length=10, null=True
            ),
        ),
    ]
