# Generated by Django 5.0.6 on 2024-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0021_alter_nist_aab_process_room_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="room_rh",
            field=models.CharField(blank=True, db_column="Room RH", max_length=10),
        ),
    ]
