# Generated by Django 5.0.6 on 2024-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0022_alter_nist_aab_process_room_rh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="left_rh",
            field=models.CharField(blank=True, db_column="Left RH", max_length=10),
        ),
        migrations.AlterField(
            model_name="nist_aab_process",
            name="left_temp",
            field=models.CharField(blank=True, db_column="Left Temp", max_length=10),
        ),
        migrations.AlterField(
            model_name="nist_aab_process",
            name="right_rh",
            field=models.CharField(blank=True, db_column="Right RH", max_length=10),
        ),
        migrations.AlterField(
            model_name="nist_aab_process",
            name="right_temp",
            field=models.CharField(blank=True, db_column="Right Temp", max_length=10),
        ),
    ]
