# Generated by Django 5.0.6 on 2024-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0023_alter_nist_aab_process_left_rh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="aab_scanner",
            field=models.CharField(blank=True, db_column="AAB Scanner", max_length=50),
        ),
    ]
