# Generated by Django 5.0.6 on 2024-10-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0024_alter_nist_aab_process_aab_scanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="date_decimal",
            field=models.CharField(
                blank=True, db_column="Date Decimal", max_length=20, null=True
            ),
        ),
    ]
