# Generated by Django 5.0.6 on 2024-10-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0025_alter_nist_aab_process_date_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meas_delay",
            field=models.CharField(blank=True, db_column="Meas Delay", max_length=20),
        ),
    ]
