# Generated by Django 5.0.6 on 2024-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0026_alter_scaling_ccc_process_meas_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="pred_c_field",
            field=models.CharField(blank=True, db_column="Pred (C)", max_length=20),
        ),
    ]
