# Generated by Django 5.0.6 on 2024-10-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0027_alter_scaling_ccc_process_pred_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="ccc_r",
            field=models.CharField(blank=True, db_column="CCC R", max_length=20),
        ),
    ]
