# Generated by Django 5.0.6 on 2024-10-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0029_alter_hr3100_process_nominal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="dvm_nplc",
            field=models.CharField(
                blank=True, db_column="DVM NPLC", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="dvm_readings",
            field=models.CharField(
                blank=True, db_column="DVM readings", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meas_temp",
            field=models.CharField(
                blank=True, db_column="Meas Temp", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meas_temp_2",
            field=models.CharField(
                blank=True, db_column="Meas Temp 2", max_length=10, null=True
            ),
        ),
    ]
