# Generated by Django 5.0.6 on 2024-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0030_alter_scaling_ccc_process_dvm_nplc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="pressure",
            field=models.CharField(
                blank=True, db_column="Pressure", max_length=20, null=True
            ),
        ),
    ]
