# Generated by Django 5.0.6 on 2024-10-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0032_alter_scaling_ccc_process_sd_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="system_id",
            field=models.CharField(
                blank=True, db_column="System ID", max_length=20, null=True
            ),
        ),
    ]
