# Generated by Django 5.0.6 on 2024-10-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0034_alter_scaling_ccc_process_sd_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="ccc_nom_ratio",
            field=models.CharField(
                blank=True, db_column="CCC Nom Ratio", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="ccc_r",
            field=models.CharField(blank=True, db_column="CCC R", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="ccc_timing",
            field=models.CharField(blank=True, db_column="CCC Timing", max_length=45),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="comments",
            field=models.TextField(blank=True, db_column="Comments"),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="date",
            field=models.CharField(blank=True, db_column="Date", max_length=100),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="dvm_nplc",
            field=models.CharField(blank=True, db_column="DVM NPLC", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="dvm_readings",
            field=models.CharField(blank=True, db_column="DVM readings", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meas_delay",
            field=models.CharField(blank=True, db_column="Meas Delay", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meas_temp",
            field=models.CharField(blank=True, db_column="Meas Temp", max_length=10),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meas_temp_2",
            field=models.CharField(blank=True, db_column="Meas Temp 2", max_length=10),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="meassets",
            field=models.CharField(blank=True, db_column="MeasSets", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="pred_c_field",
            field=models.CharField(blank=True, db_column="Pred (C)", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="pressure",
            field=models.CharField(blank=True, db_column="Pressure", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="process",
            field=models.CharField(blank=True, db_column="Process", max_length=100),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="reference_sn",
            field=models.CharField(blank=True, db_column="Reference SN", max_length=45),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="serial",
            field=models.CharField(blank=True, db_column="Serial", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="service_id",
            field=models.CharField(blank=True, db_column="Service ID", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="system_id",
            field=models.CharField(blank=True, db_column="System ID", max_length=20),
        ),
    ]
