# Generated by Django 5.0.6 on 2024-10-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0035_alter_scaling_ccc_process_ccc_nom_ratio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="area",
            field=models.CharField(blank=True, db_column="Area", max_length=20),
        ),
    ]
