# Generated by Django 5.0.6 on 2024-10-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0036_alter_scaling_ccc_process_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="sd_c_field",
            field=models.FloatField(blank=True, db_column="SD (C)", null=True),
        ),
    ]
