# Generated by Django 5.0.6 on 2024-10-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0038_alter_scaling_ccc_process_sd_c_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scaling_ccc_process",
            name="sd_c_field",
        ),
    ]
