# Generated by Django 5.0.6 on 2024-10-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0039_remove_scaling_ccc_process_sd_c_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="scaling_ccc_process",
            name="sd_c_field",
            field=models.FloatField(
                blank=True, db_column="SD (C)", default=-1, null=True
            ),
        ),
    ]
