# Generated by Django 5.0.6 on 2024-10-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0040_scaling_ccc_process_sd_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="sd_c_field",
            field=models.CharField(blank=True, db_column="SD (C)", max_length=10),
        ),
    ]
