# Generated by Django 5.0.6 on 2024-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0041_alter_scaling_ccc_process_sd_c_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)", null=True),
        ),
        migrations.AlterField(
            model_name="magnicon_ccc_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)", null=True),
        ),
        migrations.AlterField(
            model_name="thomas_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="warshawsky_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
    ]
