# Generated by Django 5.0.6 on 2024-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0042_alter_hr3100_process_nominal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="dvm_nplc",
            field=models.CharField(blank=True, db_column="DVM NPLC", max_length=10),
        ),
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="dvm_readings",
            field=models.CharField(blank=True, db_column="DVM Readings", max_length=10),
        ),
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="source_voltage",
            field=models.CharField(
                blank=True, db_column="Source Voltage", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="mi_6010b_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="mi_6010c_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="mi_6010q_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="mi_6010sw_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="mi_6020q_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
        migrations.AlterField(
            model_name="nist_aab_process",
            name="nominal",
            field=models.FloatField(blank=True, db_column="Nominal (ohm)"),
        ),
    ]
