# Generated by Django 5.0.6 on 2024-10-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0043_alter_mi_6000b_process_dvm_nplc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magnicon_ccc_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
    ]
