# Generated by Django 5.0.6 on 2024-10-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0044_alter_magnicon_ccc_process_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
    ]
