# Generated by Django 5.0.6 on 2024-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0045_alter_mi_6000b_process_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scaling_ccc_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
    ]
