# Generated by Django 5.0.6 on 2024-10-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0046_alter_scaling_ccc_process_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr3100_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
    ]
