# Generated by Django 5.0.6 on 2024-10-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0047_alter_hr3100_process_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magnicon_ccc_process",
            name="end_time",
            field=models.DateTimeField(blank=True, db_column="End Time"),
        ),
        migrations.AlterField(
            model_name="mi_6010b_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="mi_6010b_process",
            name="end_time",
            field=models.TimeField(blank=True, db_column="End Time"),
        ),
        migrations.AlterField(
            model_name="mi_6010c_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="mi_6010c_process",
            name="end_time",
            field=models.TimeField(blank=True, db_column="End Time"),
        ),
        migrations.AlterField(
            model_name="mi_6020q_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="mi_6020q_process",
            name="end_time",
            field=models.TimeField(blank=True, db_column="End Time"),
        ),
        migrations.AlterField(
            model_name="nist_aab_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="thomas_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="warshawsky_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
    ]
