# Generated by Django 5.0.6 on 2024-10-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0048_alter_magnicon_ccc_process_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mi_6000b_process",
            name="end_time",
            field=models.TimeField(blank=True, db_column="End Time"),
        ),
        migrations.AlterField(
            model_name="mi_6010q_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="mi_6010q_process",
            name="end_time",
            field=models.TimeField(blank=True, db_column="End Time"),
        ),
        migrations.AlterField(
            model_name="mi_6010sw_process",
            name="date",
            field=models.DateTimeField(blank=True, db_column="Date"),
        ),
        migrations.AlterField(
            model_name="mi_6010sw_process",
            name="end_time",
            field=models.TimeField(blank=True, db_column="End Time"),
        ),
    ]
