# Generated by Django 5.0.6 on 2024-10-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0049_alter_mi_6000b_process_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mi_6010c_process",
            name="serial",
            field=models.CharField(blank=True, db_column="Serial", max_length=50),
        ),
    ]
