# Generated by Django 5.0.6 on 2024-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0050_alter_mi_6010c_process_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mi_6010c_process",
            name="mi_stats",
            field=models.CharField(blank=True, db_column="MI Stats", max_length=50),
        ),
    ]
