# Generated by Django 5.0.6 on 2024-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0052_alter_nist_aab_process_date_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nist_aab_process",
            name="date_decimal",
            field=models.FloatField(blank=True, db_column="Date Decimal"),
        ),
    ]
