# Generated by Django 5.0.6 on 2026-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0054_alter_nist_aab_process_date_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="serial",
            field=models.CharField(
                blank=True,
                db_column="Serial",
                help_text="<em>Serial number of the standard</em>",
                max_length=40,
            ),
        ),
    ]
