# Generated by Django 5.0.6 on 2026-01-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resistors", "0055_alter_search_standard_resistor_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_standard_resistor",
            name="nominal",
            field=models.CharField(
                blank=True,
                db_column="Nominal (ohm)",
                help_text="<em>Nominal standard value in ohms</em>",
                max_length=20,
                null=True,
            ),
        ),
    ]
